export default [
  {
    id: 1,
    isClicked: false,
    img: "https://wallpapercave.com/uwp/uwp942196.jpeg",
    name: "Captain America",
  },
  {
    id: 2,
    isClicked: false,
    img: "https://wallpapercave.com/wp/wp3703399.jpg",
    name: "Iron Man",
  },
  {
    id: 3,
    isClicked: false,
    img: "https://images.unsplash.com/photo-1635805737707-575885ab0820?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
    name: "Spider-Man",
  },
  {
    id: 4,
    isClicked: false,
    img: "https://wallpaperaccess.com/full/8130474.jpg",
    name: "Scarlett Witch",
  },
  {
    id: 5,
    isClicked: false,
    img: "https://images.hdqwalls.com/wallpapers/black-widow-4k-1g.jpg",
    name: "Black Widow",
  },
  {
    id: 6,
    isClicked: false,
    img: "https://wallpapers.com/images/hd/miles-morales-falling-upside-down-turikai4inacualc.jpg",
    name: "Miles Morales",
  },
  {
    id: 7,
    isClicked: false,
    img: "https://images.herzindagi.info/image/2022/Nov/black-panther-wakanda-forever-twitter-reactions.jpg",
    name: "Black Panther",
  },
  {
    id: 8,
    isClicked: false,
    img: "https://images.unsplash.com/photo-1596727147705-61a532a659bd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80",
    name: "Groot",
  },
  {
    id: 9,
    isClicked: false,
    img: "https://www.wallpaperup.com/uploads/wallpapers/2015/07/11/748480/c456b0fc0d0efdc3cfbe0bfdc94681c8.jpg",
    name: "Ant Man",
  },
  {
    id: 10,
    isClicked: false,
    img: "https://images8.alphacoders.com/121/1214264.jpg",
    name: "Moon Knight",
  },
  {
    id: 11,
    isClicked: false,
    img: "https://www.mordeo.org/files/uploads/2020/01/Thanos-Artwork-4K-Ultra-HD-Mobile-Wallpaper-950x1689.jpg",
    name: "Thanos",
  },
  {
    id: 12,
    isClicked: false,
    img: "https://e1.pxfuel.com/desktop-wallpaper/878/285/desktop-wallpaper-multiverse-doctor-strange-illusions.jpg",
    name: "Doctor Strange",
  },
  {
    id: 13,
    isClicked: false,
    img: "https://w0.peakpx.com/wallpaper/801/442/HD-wallpaper-thor-marvel.jpg",
    name: "Thor",
  },
  {
    id: 14,
    isClicked: false,
    img: "https://c4.wallpaperflare.com/wallpaper/365/746/474/claws-hugh-jackman-origins-wallpaper-preview.jpg",
    name: "Wolverine",
  },
  {
    id: 15,
    isClicked: false,
    img: "https://mobimg.b-cdn.net/v3/fetch/ba/ba9b53af5b2678431dec3eec428ab483.jpeg",
    name: "Gambit",
  },
  {
    id: 16,
    isClicked: false,
    img: "https://cdn.vox-cdn.com/uploads/chorus_asset/file/24348750/Screen_Shot_2023_01_09_at_10.24.40_PM.png",
    name: "Kang",
  },
  {
    id: 17,
    isClicked: false,
    img: "https://wallpapercave.com/wp/wp8387570.jpg",
    name: "Loki",
  },
  {
    id: 18,
    isClicked: false,
    img: "https://w0.peakpx.com/wallpaper/155/849/HD-wallpaper-hawkeye-arquero-ronin.jpg",
    name: "Hawkeye",
  },
  {
    id: 19,
    isClicked: false,
    img: "https://images.hdqwalls.com/download/incredible-hulk-4k-qj-1920x1080.jpg",
    name: "Hulk",
  },
  {
    id: 20,
    isClicked: false,
    img: "https://images7.alphacoders.com/107/1074481.jpg",
    name: "Star-Lord",
  },
  {
    id: 21,
    isClicked: false,
    img: "https://www.motionpictures.org/wp-content/uploads/2022/10/SRE6160_TRL_comp_wta_v0346.1025.jpg",
    name: "Namor",
  },
];
